eureka:
  client:
    service-url:
      defaultZone ： http ： // eureka8001 ： 8001 / eureka /，http ： // eureka8002 ： 8002 / eureka
server:
  port: 8787
spring:
  application:
    name: service-ribb6666
